name: Fake Container Deploy
on:
  pull_request_review:
    types: [submitted]

jobs:
  test-deploy:

    runs-on: ubuntu-latest
    if: github.event.review.state == 'approved'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Display Docker image name
        run: "echo Docker image would be: $IMAGE"
        env:
          IMAGE: ${{ github.repository }}:${{ github.head_ref }}"
