name: CI/CD build and run tests
on:
  push:
    branches:
      - main
      - feature_location_update
      - Staging
jobs:
  build:
    runs-on: ubuntu-latest
    environment: carpooltaxi

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: temurin

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@ccb4328a959376b642e027874838f60f8e596de3

      - name: Make Gradlew Executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        uses: gradle/gradle-build-action@749f47bda3e44aa060e82d7b3ef7e40d953bd629

      - name: run unit tests
        run: |
          ./gradlew test
          

  integrationTest:
    runs-on: ubuntu-latest
    needs:
      - build
    environment: carpooltaxi

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run integration tests
        run: |
          ./gradlew integrationTest

  bootJar:
    runs-on: ubuntu-latest
    needs:
      - integrationTest
    environment: carpooltaxi

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: bootJar
        run: |
          ./gradlew bootJar
          
      - name: Upload Jar
        uses: actions/upload-artifact@v3
        with:
          name: app
          path: build/libs/carpooltaxi-0.0.1-SNAPSHOT.jar

  systemTest:
    runs-on: ubuntu-latest
    needs: bootJar
    environment: carpooltaxi
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Jar
        uses: actions/download-artifact@v3
        with:
          name: app

      - name: run-app
        run: |
          java -jar carpooltaxi-0.0.1-SNAPSHOT.jar &

      - name: Run all system tests
        run: |
          ./gradlew systemTest